[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean", "readme"]

[tasks.readme]
command = "cargo"
args = ["readme","-o","README.md"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = []

[tasks.test-release]
command = "cargo"
args = ["test", "--release"]

[tasks.bench_ascii_decoding]
command = "cargo"
args = ["bench", "--bench", "ascii_decoding"]

[tasks.bench_utf8_decoding]
command = "cargo"
args = ["bench", "--bench", "utf8_decoding"]
