[workspace]
members = ["chisel-json", "chisel-decoders"]
resolver="2"

[workspace.package]
version="1.0.8"
edition="2021"
authors = ["Jonny Coombes <jcoombes@jcs-software.co.uk>"]
rust-version="1.56"
