[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean", "readme"]

[tasks.readme]
command = "cargo"
args = ["readme","-o","README.md"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = []

[tasks.profile]
command = "./profile.sh"
args = []
dependencies = []

[tasks.test-release]
command = "cargo"
args = ["test", "--release"]
dependencies = []

[tasks.bench_json_lexer]
command = "cargo"
args = ["bench", "--bench", "json_lexer"]

[tasks.bench_scanner]
command = "cargo"
args = ["bench", "--bench", "scanner"]
