name: Chisel-Core CI

on:
  push:
    branches: [ "dev", "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Cargo Make
      run: cargo install cargo-make
    - name: Make Test
      run: cargo make test
